name: Build

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        name: [Linux]
        os: [ubuntu-latest]

    name: Build for ${{ matrix.name }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install, Test and Build
        run: |
          cd src-react
          pnpm install
          pnpm test
          pnpm build
          pnpm build-ssr

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
    
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2

      - name: Test
        run: |
          gradle test
